### ISSUE TITLE
code & dataset release?

### ISSUE THREAD

**Issue by zozobozo** [tom-roddick/mono-semantic-maps#1]
Hi Tom,

That's great work!  
I would love to play around with the data and models :)

Do you plan to release anytime soon the following?
1. the dataset-creation pipeline from ArgoVerse and NuScenes
2. the created dataset (ground-truth maps etc.)
3. your networks and models.

I think all of the above would be of great value to the community.
Are you planning to do that soon? Or is it dependent on the paper first being published?

Thanks a lot!
Z.

**Comment by patrick-llgc** [comment]
Agree with what @zozobozo said. 

Great work on pushing this frontier a bit further, and congratulations on being accepted to CVPR 2020 as an oral paper. I watched your presentation and the results look really impressive. I am really looking forward to the release of the dataset and the codebase.

**Comment by Kaahan** [comment]
Same as the above; the dataset generation is of particular interest!

**Comment by placeforyiming** [comment]
Hope to see it soon

**Comment by ConanCui** [comment]
Wait to see the code

**Comment by pieteroyens** [comment]
I would like to chime in with the above comments; great paper and eagerly awaiting code! I imagine not only the results but also the ground truth data generation is of particular interest to many people.

**Comment by tom-roddick** [comment]
Hi all! Thanks for your interest in the paper! I'm sorry that it's take me so long to upload the code, unfortunately I wasn't able to before due to other commitments, but the code is now available. Many thanks for your patience.
